[project]
name = "agent-folder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-adk>=1.19.0",
    "google-genai>=1.52.0",
    "fastapi>=0.109.0",
    "uvicorn>=0.27.0",
    "youtube-transcript-api>=0.6.2",
]
